# Generated by Django 5.0.4 on 2024-05-20 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.IntegerField(choices=[(0, 'Web-application'), (1, 'API'), (2, 'Mobile-app')])),
                ('attackT', models.IntegerField(choices=[(0, 'Reflected'), (1, 'Stored'), (2, 'Dom-based')])),
                ('skill', models.IntegerField(choices=[(0, 'Beginner'), (1, 'Intermediate'), (2, 'Advanced')])),
                ('automation', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('platform', models.IntegerField(choices=[(0, 'Windows'), (1, 'Linux'), (2, 'MacOS')])),
                ('suggest', models.IntegerField(choices=[(0, 'Nmap & OWASP ZAP'), (1, 'Nmap & XSSser')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
