# Generated by Django 5.0.4 on 2024-06-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestxss', '0002_alter_userdata_suggest_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='preferred_suggestion',
            field=models.IntegerField(blank=True, choices=[(0, 'Nmap & OWASP ZAP'), (1, 'Nmap & XSSer')], null=True),
        ),
    ]
