# Generated by Django 5.0.4 on 2024-06-09 04:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestxss', '0003_feedback_preferred_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='preferred_suggestion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
