# Generated by Django 5.0.4 on 2024-06-30 04:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestxss', '0007_toolresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
