# Generated by Django 5.0.4 on 2024-08-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestxss', '0008_userdata_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='suggest',
            field=models.IntegerField(choices=[(0, 'Nmap & PwnXSS'), (1, 'Nmap & XSStrike'), (2, 'Nmap & Burp Suite'), (3, 'Nmap & OWASP ZAP')]),
        ),
    ]
